# Generated by Django 2.2.6 on 2021-02-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210202_1151'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Issue',
        ),
    ]
