# Generated by Django 2.2.6 on 2021-02-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210202_0816'),
        ('task', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='header',
            field=models.CharField(default='Не подписано', max_length=65, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='Короткое название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Team', verbose_name='Команда, работающая над проектом'),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_task', to='user.User', verbose_name='Составил'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor_task', to='user.User', verbose_name='Выполняет'),
        ),
        migrations.AddField(
            model_name='task',
            name='header',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Project'),
        ),
        migrations.AddField(
            model_name='task',
            name='short_name',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='Короткое название'),
            preserve_default=False,
        ),
    ]
