# Generated by Django 2.2.6 on 2021-02-02 09:39

import WatchT.apps.abstract.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20210202_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='got_minutes',
            field=models.IntegerField(default=1, validators=[WatchT.apps.abstract.validators.is_int_validate, WatchT.apps.abstract.validators.bigger_than_zero_validate]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='Родительская задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='want_minutes',
            field=models.IntegerField(default=1, validators=[WatchT.apps.abstract.validators.is_int_validate, WatchT.apps.abstract.validators.bigger_than_zero_validate]),
            preserve_default=False,
        ),
    ]
