# Generated by Django 2.2.6 on 2021-02-02 09:49

import WatchT.apps.abstract.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20210202_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(default=1, validators=[WatchT.apps.abstract.validators.is_int_validate, WatchT.apps.abstract.validators.bigger_than_zero_validate], verbose_name='Уровень вложенности'),
        ),
    ]
