# Generated by Django 2.2.6 on 2021-02-03 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание команды')),
            ],
            options={
                'verbose_name': 'Команда сотрудников',
                'verbose_name_plural': 'Команды сотрудников',
            },
        ),
        migrations.CreateModel(
            name='User2Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка Пользователь -> Команда',
                'verbose_name_plural': 'Связки Пользователь -> Команда',
            },
        ),
    ]
