# Generated by Django 2.2.6 on 2021-02-02 11:31

import WatchT.apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=WatchT.apps.user.models.user_photo_upload_to)),
                ('role', models.IntegerField(choices=[(0, 'Гость'), (1, 'Разработчик'), (2, 'Аналитик'), (3, 'Тимлид'), (4, 'Администратор сайта')], default=0, verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание команды')),
            ],
            options={
                'verbose_name': 'Команда сотрудников',
                'verbose_name_plural': 'Команды сотрудников',
            },
        ),
        migrations.CreateModel(
            name='User2Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CustomUser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка Пользователь -> Команда',
                'verbose_name_plural': 'Связки Пользователь -> Команда',
            },
        ),
    ]
