# Generated by Django 2.2.6 on 2021-02-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210202_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Расширение пользователя', 'verbose_name_plural': 'Расширения пользователей'},
        ),
    ]
