# Generated by Django 2.2.6 on 2021-02-02 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210202_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Команда сотрудников',
                'verbose_name_plural': 'Команды сотрудников',
            },
        ),
    ]
