# Generated by Django 2.2.6 on 2021-02-08 13:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210208_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='id',
            field=models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
