# Generated by Django 2.2.6 on 2021-02-02 08:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание команды'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=1, max_length=65, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Никнейм'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User2Team',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка Пользователь -> Команда',
                'verbose_name_plural': 'Связки Пользователь -> Команда',
            },
        ),
    ]
