# Generated by Django 2.2.6 on 2021-02-02 09:58

import WatchT.apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210202_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to=WatchT.apps.user.models.user_photo_upload_to),
            preserve_default=False,
        ),
    ]
