# Generated by Django 2.2.6 on 2021-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Гость'), (1, 'Разработчик'), (2, 'Аналитик'), (3, 'Тимлид'), (4, 'Администратор сайта')], default=0, verbose_name='Роль'),
        ),
    ]
