# Generated by Django 2.2.6 on 2021-02-25 07:12

import WatchT.apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='user/default_user_pic.jpg', upload_to=WatchT.apps.user.models.user_photo_upload_to, verbose_name='Фото')),
                ('role', models.IntegerField(choices=[(0, 'Гость'), (1, 'Разработчик'), (2, 'Аналитик'), (3, 'Тимлид'), (4, 'Администратор сайта')], default=0, verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
