# Generated by Django 2.2.6 on 2021-03-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210325_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeuser',
            name='photo',
        ),
    ]
