# Generated by Django 2.2.12 on 2021-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_employeeuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Гость'), (1, 'Разработчик'), (2, 'Проектный менеджер'), (3, 'Тимлид'), (4, 'Администратор сайта')], default=0, verbose_name='Роль'),
        ),
    ]
