# Generated by Django 2.2.12 on 2021-04-20 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210402_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('skill', models.IntegerField(choices=[(0, 'Фронтенд'), (1, 'Бэкенд'), (2, 'Девопс'), (3, 'Мобайл'), (4, 'БД'), (5, 'Сисадмин')], verbose_name='Навык')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.EmployeeUser', verbose_name='Сотрудник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
