# Generated by Django 2.2.12 on 2021-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0009_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue.IssueType',
                                    verbose_name='Навык'),
        ),
    ]
