# Generated by Django 2.2.12 on 2021-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210420_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='level',
            field=models.IntegerField(choices=[(0, 'Стажер'), (1, 'Джуниор'), (2, 'Миддл'), (3, 'Сеньор')], default=1, verbose_name='Позиция'),
        ),
    ]
