# Generated by Django 2.2.12 on 2021-03-06 17:50

import WatchT.apps.abstract.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='want_buffer_minutes',
            field=models.IntegerField(default=0, validators=[WatchT.apps.abstract.validators.is_int_validate, WatchT.apps.abstract.validators.non_negative_int_validate], verbose_name='Буфер оценки'),
            preserve_default=False,
        ),
    ]
