# Generated by Django 2.2.12 on 2021-03-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_auto_20210306_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.Issue', verbose_name='Родительская задача'),
        ),
    ]
