# Generated by Django 2.2.12 on 2021-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20210306_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktime',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание работы'),
        ),
    ]
