# Generated by Django 2.2.6 on 2021-03-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_projectstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatistics',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Проект'),
        ),
    ]
