# Generated by Django 2.2.6 on 2021-03-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_auto_20210323_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStatistics',
        ),
    ]
