# Generated by Django 2.2.6 on 2021-03-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_delete_projectstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited',
        ),
    ]
