# Generated by Django 2.2.12 on 2021-04-20 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0012_issue_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('typo', models.IntegerField(choices=[(0, 'Фронтенд'), (1, 'Бэкенд'), (2, 'Девопс'), (3, 'Мобайл'), (4, 'БД'), (5, 'Сисадмин')], verbose_name='Тип')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='typo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issue.IssueType', verbose_name='Тип задачи'),
            preserve_default=False,
        ),
    ]
