# Generated by Django 2.2.12 on 2021-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0013_auto_20210420_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='typo',
            field=models.IntegerField(choices=[(0, 'Фронтенд'), (1, 'Бэкенд'), (2, 'Девопс'), (3, 'Мобайл'), (4, 'БД'), (5, 'Сисадмин')], unique=True, verbose_name='Тип'),
        ),
    ]
