# Generated by Django 2.2.12 on 2021-04-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0014_auto_20210420_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuetype',
            options={'verbose_name': 'Тип задачи', 'verbose_name_plural': 'Типы задач'},
        ),
    ]
